apiVersion: apps/v1
kind: Deployment
metadata:
  name: sushiman
spec:
  selector:
    matchLabels:
      app: sushiman
  template:
    metadata:
      labels:
        app: sushiman
    spec:
      containers:
      - name: sushiman
        image: viniciuscaol/sushiman:v{{TAG}}
        ports:
        - containerPort: 80